### ISSUE TITLE
24 GB VRAM insufficient

### ISSUE THREAD

**Issue by petertapler** [Sentdex/OpenAssistant_API_Pythia_12B#2]
Using an nvidia P40 when starting the API script the following error message occurs.

(GPU is not used for video output, all 24 GB VRAM is available)

```
Traceback (most recent call last):
  File "/home/user/repos/OpenAssistant_API_Pythia_12B/oasstapiv1.py", line 24, in <module>
    model = model.half().cuda()
            ^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 905, in cuda
    return self._apply(lambda t: t.cuda(device))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/home/user/.local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 820, in _apply
    param_applied = fn(param)
                    ^^^^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 905, in <lambda>
    return self._apply(lambda t: t.cuda(device))
                                 ^^^^^^^^^^^^^^
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 492.00 MiB (GPU 0; 22.38 GiB total capacity; 21.72 GiB already allocated; 485.06 MiB free; 21.74 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

```

Tried defining different sizes 'max_split_size_mb' for torch to maybe reduce memory fragmentation. Did not work.

Edit: Rewatched your video, the model was taking up over 25 GB of VRAM.

**Comment by AdeebAldkheel** [comment]
if your GPU not using any other application and still facing the same error you can try to reduce VRAM usage in Pytorch:
One way is to use model.eval() with torch.no_grad() on your target machine when making predictionsmodel.eval() will switch model layers to eval mode and torch.no_grad() will deactivate the autograd engine, reducing memory usage 
(https://stackoverflow.com/questions/57942507/how-to-save-gpu-memory-usage-in-pytorch)
(https://stackoverflow.com/questions/57942507/how-to-save-gpu-memory-usage-in-pytorch). 
Another way is to control the batch size of your model
(https://stackoverflow.com/questions/49529372/force-gpu-memory-limit-in-pytorch)
(https://stackoverflow.com/questions/49529372/force-gpu-memory-limit-in-pytorch). 
You could also try using PyTorch’s automatic mixed precision library
(https://stackoverflow.com/questions/66475902/how-can-i-decrease-dedicated-gpu-memory-usage-and-use-shared-gpu-memory-for-cuda)
